[1mdiff --git a/README.md b/README.md[m
[1mindex 2e6493f..8bc385c 100644[m
[1m--- a/README.md[m
[1m+++ b/README.md[m
[36m@@ -1,5 +1,6 @@[m
 solutions in c:[m
 [m
[32m+[m[32m    strextr.c           -- extracting text between one string and another[m
     keystate.c          -- example use of GetAsyncKeyState() WinAPI to record keystrokes, for educational purposes[m
     keystatereader.c    -- read the recorded keystrokes from log generated by keystate[m
     fullscreen.c        -- an attempt to force a window into maximized/fullscreen mode[m
[36m@@ -14,7 +15,7 @@[m [msolutions in c:[m
     helloworld.c[m
 [m
 solutions in cs:[m
[31m-    [m
[32m+[m
     viper.cs                        -- a vulnerability scanner for searching obsolete products in an enterprise domain environment[m
     assemblyinfo.cs                 -- example use for including assembly info within an application[m
     bitmasker.cs                    -- convert any file to base64 format[m
[36m@@ -26,7 +27,7 @@[m [msolutions in cs:[m
     htmlremover.cs                  -- removing html from a file[m
     httpserver.cs                   -- a simple http server[m
     iniparser.cs                    -- parser for reading configuration files[m
[31m-    matrix.cs                       -- just for fun, display the matrix effect from the film [m
[32m+[m[32m    matrix.cs                       -- just for fun, display the matrix effect from the film[m
     server.cs                       -- a simple server[m
     colorizestring.cs               -- example use for coloring strings[m
     datagridview_selectedvalue.cs   -- retrieving value of datagridview index[m
[36m@@ -36,7 +37,7 @@[m [msolutions in cs:[m
     mysqlconnector.cs               -- simple library for handling mysql server interactions[m
     randomnumber.cs                 -- generating random numbers[m
     reportgenerator.cs              -- converts text files to pdf using migradoc library[m
[31m-    userlogin.cs                    -- simple user login form [m
[32m+[m[32m    userlogin.cs                    -- simple user login form[m
     filereader.cs                   -- open file for reading[m
     filewriter.cs                   -- open file for writing[m
     sendmail.cs                     -- sending mail with google smtp[m
[36m@@ -61,7 +62,7 @@[m [msolutions in java:[m
     boa.java                       -- a remote management tool      [m
     displaymodes.java              -- setting display modes[m
     filecheck.java                 -- check if file exists[m
[31m-    [m
[32m+[m
 solutions in javascript:[m
 [m
     checkbox.js         -- retrieving items from checkbox[m
[36m@@ -76,7 +77,7 @@[m [msolutions in javascript:[m
     ticker.js           -- news ticker example[m
     typer.js            -- typewriter effect within textarea[m
     urlparameters.js    -- pass checkbox items to url parameters[m
[31m-    [m
[32m+[m
 solutions in powershell:[m
 [m
     getprinters.ps1     -- retrieve list of installed printers[m
[36m@@ -101,6 +102,3 @@[m [msolutions in php:[m
     imageformat.php         -- identifying image file format[m
     generatefn.php          -- generate random file name[m
     listboxswap.php         -- moving objects between listboxes[m
[31m-[m
[31m-[m
[31m-[m
